In [3]:
!pip install numpy pandas matplotlib


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import sys
print(sys.executable)


C:\Users\Asus\AppData\Local\Programs\Python\Python313\python.exe


In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("Работает ✅")

Matplotlib is building the font cache; this may take a moment.


Работает ✅


In [6]:
array_1d = np.arange(1, 11)
print("1D массив:", array_1d)

array_2d = np.random.randint(1, 10, size=(3, 3))
print("2D массив:\n", array_2d)


1D массив: [ 1  2  3  4  5  6  7  8  9 10]
2D массив:
 [[8 5 1]
 [5 5 7]
 [4 6 8]]


In [7]:
print("Сумма:", array_1d.sum())
print("Среднее:", array_1d.mean())
print("Максимум:", array_1d.max())


Сумма: 55
Среднее: 5.5
Максимум: 10


In [8]:
multiplied_array = array_1d * 2
print("Умножено на 2:", multiplied_array)


Умножено на 2: [ 2  4  6  8 10 12 14 16 18 20]


In [9]:
modified_array = array_1d.copy()
modified_array[modified_array > 5] = 0
print("Значения > 5 заменены на 0:", modified_array)


Значения > 5 заменены на 0: [1 2 3 4 5 0 0 0 0 0]
